# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='fecha_publicado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=5),
        ),
        migrations.AddField(
            model_name='libro',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='superventas',
            field=models.BooleanField(default=False),
        ),
    ]
