# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 15:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_auto_20160717_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='agregado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
