# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 16:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_libro_agregado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
